### PR TITLE
Feat: Use correct default materials on URP/HDRP

### PR DESCRIPTION
**Pull request by hybridherbst**
This PR adds URP/HDRP out-of-the-box support by using the correct materials. They are loaded from GUIDs, same as URP/HDRP do. Not sure if there's a cleaner way.

### CODE REVIEW

**Comment by keijiro** [comment]
How about using `RenderPipelineAsset.defaultMaterial` instead of GUID? I have never tried it, though.

https://docs.unity3d.com/ScriptReference/Rendering.RenderPipelineAsset-defaultMaterial.html

**Comment by hybridherbst** [comment]
Interesting, I'll try that - I wonder why the SRPs aren't using it for material import though 🤔

**Comment by hybridherbst** [comment]
Seems to work! Thanks for the tip, that's much simpler / cleaner / future proof.

**Comment by keijiro** [comment]
Thanks. Good to know that it works as intended.

**Pull request merged**
